apiVersion: apps/v1
kind: Deployment
metadata:
  name: datavission-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: datavission
  template:
    metadata:
      labels:
        app: datavission
    spec:
      containers:
      - name: datavission-container
        image: your-image:tag
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: datavission-service
spec:
  type: LoadBalancer
  selector:
    app: datavission
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:datavission-ingress
spec:
  rules:
  - host: 8a43d28b0820e6f30221e3943ded5638k8sengineers.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: datavission-service
            port:
              number: 80

