kind: ConfigMap
apiVersion: v1
metadata:
  name: flask-app-content
  labels:
    app: flask-app-content
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>{{ .Release.Name }}</title>
        <link rel="stylesheet" href="main.css">
      </head>
      <body>
        <h1>Hello from my ConfigMap!</h1>
      </body>
    </html>
  main.css: |
    body {
      background-color: rgb(224,224,224);
      font-family: Verdana, Arial, Helvetica, sans-serif;
      font-size: 100%;
    }