apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-app
      name: flask-app
    spec:
      containers:
        - name: flask-app
          image: lioratari/myflaskapp:latest
          volumeMounts:
            - readOnly: true
              mountPath: /app/templates
              name: html-files
          ports:
          - containerPort: 9000
      volumes:
        - name: html-files
          configMap:
            name: flask-app-content